server:
  port: 10010
spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1 #默认注册地址
zuul:
  prefix: /api # 添加路由前缀
  routes:
    user-service:
      path: /user/**
      strip-prefix: false #过滤掉匹配路径 访问不需要/user/user/1   变成/user/1
  ignored-services: #忽略的服务请求 consumer不可访问
    - consumer