server:
  port: 10086 # 端口
spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中显示
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
    register-with-eureka: true # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: true # 是否拉取其它服务的信息，默认是true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1 #默认注册地址
  server:
    enable-self-preservation: true # 开发时关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 1000 # 扫描失效服务的间隔时间（缺省为60*1000ms）